# Generated by Django 4.2 on 2023-04-24 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(blank=True, max_length=1000, null=True)),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('card', models.CharField(blank=True, max_length=1000, null=True)),
                ('funds', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('price', models.IntegerField()),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='passenger', related_query_name='passenger', to='users.passenger')),
            ],
        ),
    ]
