# Generated by Django 4.1.8 on 2023-04-24 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travel',
            name='passenger',
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='passenger', related_query_name='passenger', to='users.passenger')),
                ('travel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='passenger', related_query_name='passenger', to='users.travel')),
            ],
        ),
    ]
