# Generated by Django 4.1.8 on 2023-04-25 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_travel_passenger_bus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='passenger',
        ),
        migrations.AlterField(
            model_name='bus',
            name='travel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='travel', related_query_name='travel', to='users.travel'),
        ),
        migrations.CreateModel(
            name='Captine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('travel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='travel1', related_query_name='travel1', to='users.travel')),
            ],
        ),
        migrations.AddField(
            model_name='bus',
            name='captine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='captine', related_query_name='captine', to='users.captine'),
        ),
        migrations.AddField(
            model_name='bus',
            name='passenger',
            field=models.ManyToManyField(blank=True, null=True, to='users.passenger'),
        ),
    ]
