# Generated by Django 4.1.8 on 2023-05-29 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_captine_bus_no_alter_bus_id_alter_captine_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
