# Generated by Django 4.1.8 on 2023-05-29 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_passenger_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='phone',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
